export interface Product {
  id: string;
  slug: string;
  title: string;
  series: "tarpe-diem" | "sil-vous-bled";
  price: number;
  currency: string;
  image: string;
  isNew?: boolean;
  description?: string;
  dimensions?: string;
  paper?: string;
}

export const products: Product[] = [
  // === TARPE DIEM SERIES (40) ===
  {
    id: "td-001",
    slug: "tarpe-diem",
    title: "Tarpe Diem",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-tarpe-diem-v2.webp",
    isNew: true,
    description: "The flagship manifesto. When carpe diem meets systemic collapse.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-002",
    slug: "notre-diams",
    title: "Notre Diams",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-notre-diams.webp",
    isNew: true,
    description: "Holy diamonds. Sacred bling for the spiritually bankrupt.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-003",
    slug: "en-haut-trouple",
    title: "En Haut Trouple",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-en-haut-trouple.webp",
    isNew: true,
    description: "High triple. When altitude meets awkward geometry.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-004",
    slug: "gate-rich",
    title: "Gate Rich",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-gate-rich.webp",
    description: "Get rich or die trying? How about gate rich and watch capitalism eat itself.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-005",
    slug: "flamingoat",
    title: "Flamingoat",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-flamingoat.webp",
    description: "Part flamingo, part goat, fully unhinged.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-006",
    slug: "la-loi-du-fluor",
    title: "La Loi du Fluor",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-la-loi-du-fluor.webp",
    description: "The law of fluorine. Because even chemistry has hierarchy issues.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-007",
    slug: "lame-soeur",
    title: "L'\u00c2me S\u0153ur",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-lame-soeur.webp",
    description: "Soulmate or blade sister? Depends on your French pronunciation.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-008",
    slug: "self-mad-man",
    title: "Self Mad Man",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-self-mad-man.webp",
    description: "The self-made man, but make it unhinged.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-009",
    slug: "poulpe-fiction",
    title: "Poulpe Fiction",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-poulpe-fiction.webp",
    description: "Royale with tentacles. Jules Winnfield would be confused.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-010",
    slug: "la-coke-d-azur",
    title: "La Coke d'Azur",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-la-coke-d-azur.webp",
    description: "C\u00f4te d'Azur's darker twin. Sun, sea, and something suspicious in the champagne.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-011",
    slug: "erreur-400-cables",
    title: "Erreur 400 C\u00e2bles",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-erreur-400-cables.webp",
    description: "Bad request, 400 cables. The internet is physically falling apart.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-012",
    slug: "conflit-de-canards",
    title: "Conflit de Canards",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-conflit-de-canards-v2.webp",
    description: "Duck conflict. Waterfowl warfare at its finest.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-013",
    slug: "2-canards-amis-amis",
    title: "2 Canards Amis Amis",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-2-canards-amis-amis.webp",
    description: "Two ducks, friends friends. Reduplication for emphasis.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-014",
    slug: "plan-de-coupe",
    title: "Plan de Coupe",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-plan-de-coupe.webp",
    description: "Cutting plan. Architecture meets surgical precision.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-015",
    slug: "mental-haut",
    title: "Mental Haut",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-mental-haut-v2.webp",
    description: "High mental. When your mind lives on the top floor.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-016",
    slug: "manifist-or-die",
    title: "Manifist or Die",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-manifist-or-die.webp",
    description: "Manifest or die trying. Protest as existential necessity.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-017",
    slug: "acid-en-tailleur",
    title: "Acid en Tailleur",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-acid-en-tailleur-v2.webp",
    description: "Acid in a suit. Because even chaos dresses for dinner.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-018",
    slug: "add-vitam",
    title: "Add Vitam",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-add-vitam.webp",
    description: "To life, with added vitamins. A satirical toast to longevity.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-019",
    slug: "adepte-du-cross-feet",
    title: "Adepte du Cross-Feet",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-adepte-du-cross-feet.webp",
    description: "CrossFit disciple with two left feet. Fitness meets French farce.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-020",
    slug: "allee-jacta-est",
    title: "All\u00e9e Jacta Est",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-allee-jacta-est.webp",
    description: "The die is cast, down the alley. Caesar meets suburban anxiety.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-021",
    slug: "copier-retourner",
    title: "Copier Retourner",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-copier-retourner.webp",
    description: "Copy, paste, invert. Plagiarism as a creative strategy.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-022",
    slug: "cuir-code",
    title: "Cuir Code",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-cuir-code-v2.webp",
    description: "Leather dress code. Fashion meets fetish meets French punnery.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-023",
    slug: "flamme-fatale",
    title: "Flamme Fatale",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-flamme-fatale.webp",
    description: "Fatal flame. When romance becomes a fire hazard.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-024",
    slug: "freeze-bee",
    title: "Freeze Bee",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-freeze-bee.webp",
    description: "Frozen bee. Climate change meets insect apocalypse.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-025",
    slug: "full-metal-jacket",
    title: "Full Metal Jacket",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-full-metal-jacket.webp",
    description: "Kubrick reimagined. Military industrial absurdity.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-026",
    slug: "gollm",
    title: "Gollm",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-gollm.webp",
    description: "My precious, but make it French. Tolkien meets banlieue.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-027",
    slug: "hamlet-again",
    title: "Hamlet Again",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-hamlet-again.webp",
    description: "To be or not to be, encore. Shakespeare's existential encore.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-028",
    slug: "homotetines",
    title: "Homot\u00e9tines",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-homotetines.webp",
    description: "Homothety meets tiny. Geometric humor at its most microscopic.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-029",
    slug: "ia-venerative",
    title: "IA V\u00e9n\u00e9rative",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-ia-venerative.webp",
    description: "AI worship. When machines become the new gods.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-030",
    slug: "ketastrophe",
    title: "K\u00e9tastrophe",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-ketastrophe.webp",
    description: "Ketamine catastrophe. Psychedelic disaster in one syllable.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-031",
    slug: "kung-flou",
    title: "Kung Flou",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-kung-flou.webp",
    description: "Kung fu, but blurry. Martial arts meet myopia.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-032",
    slug: "laitage-mahal",
    title: "Laitage Mahal",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-laitage-mahal.webp",
    description: "Dairy Taj Mahal. When cheese meets architectural wonder.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-033",
    slug: "le-bit-cogne",
    title: "Le Bit Cogne",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-le-bit-cogne-v2.webp",
    description: "The beat hits. Cryptocurrency meets physical violence.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-034",
    slug: "love-frontal",
    title: "Love Frontal",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-love-frontal.webp",
    description: "Head-on love. No subtlety, just collision.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-035",
    slug: "make-ricard-rain-again",
    title: "Make Ricard Rain Again",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-make-ricard-rain-again.webp",
    description: "Pastis precipitation. When ap\u00e9ro becomes political.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-036",
    slug: "pop-art",
    title: "Pop Art",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-pop-art.webp",
    description: "Pop art, literally. When the genre becomes the subject.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-037",
    slug: "queer-code",
    title: "Queer Code",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-queer-code.webp",
    description: "Queer coding. When identity becomes source code.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-038",
    slug: "scale-is-the-limit",
    title: "Scale is the Limit",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-scale-is-the-limit.webp",
    description: "The sky is no longer the limit. Scaling is.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-039",
    slug: "smoking-beach",
    title: "Smoking Beach",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-smoking-beach.webp",
    description: "Beach on fire. Climate change served with sunscreen.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-040",
    slug: "tant-de-laine",
    title: "Tant de Laine",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-tant-de-laine.webp",
    description: "So much wool. The textile industry gets philosophical.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "td-041",
    slug: "toutancamion",
    title: "Toutancamion",
    series: "tarpe-diem",
    price: 35,
    currency: "EUR",
    image: "/images/tarpe-diem/tarpe-diem-toutancamion.webp",
    description: "Tutankhamun, but it's a truck. Ancient Egypt meets logistics.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },

  // === S'IL VOUS BLED SERIES (9) ===
  {
    id: "svb-001",
    slug: "s-il-vous-bled",
    title: "S'il Vous Bled",
    series: "sil-vous-bled",
    price: 35,
    currency: "EUR",
    image: "/images/sil-vous-bled/s-il-vous-bled-s-il-vous-bled.webp",
    isNew: true,
    description: "The flagship of the series. If you please, bleed a little.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "svb-002",
    slug: "bled-runner",
    title: "Bled Runner",
    series: "sil-vous-bled",
    price: 35,
    currency: "EUR",
    image: "/images/sil-vous-bled/s-il-vous-bled-bled-runner.webp",
    isNew: true,
    description: "Running from the bled. Blade Runner meets North African suburbs.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "svb-003",
    slug: "abu-tapis",
    title: "Abu Tapis",
    series: "sil-vous-bled",
    price: 35,
    currency: "EUR",
    image: "/images/sil-vous-bled/s-il-vous-bled-abu-tapis.webp",
    isNew: true,
    description: "Abu Tapis. The carpet merchant of dystopia.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "svb-004",
    slug: "tajine",
    title: "Tajine",
    series: "sil-vous-bled",
    price: 35,
    currency: "EUR",
    image: "/images/sil-vous-bled/s-il-vous-bled-tajine.webp",
    description: "Slow-cooked satire. Served with a side of cultural fusion.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "svb-005",
    slug: "chou-crane",
    title: "Chou Cr\u00e2ne",
    series: "sil-vous-bled",
    price: 35,
    currency: "EUR",
    image: "/images/sil-vous-bled/s-il-vous-bled-chou-crane.webp",
    description: "Cabbage skull or sweet skull? Phonetic ambiguity at its finest.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "svb-006",
    slug: "djinn-tonic",
    title: "Djinn Tonic",
    series: "sil-vous-bled",
    price: 35,
    currency: "EUR",
    image: "/images/sil-vous-bled/s-il-vous-bled-djinn-tonic.webp",
    description: "Gin \u0026 tonic, but make it supernatural. Spirits within spirits.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "svb-007",
    slug: "medicis",
    title: "M\u00e9dicis",
    series: "sil-vous-bled",
    price: 35,
    currency: "EUR",
    image: "/images/sil-vous-bled/s-il-vous-bled-medicis.webp",
    description: "The Medici family, but from the banlieue. Power meets concrete.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "svb-008",
    slug: "bsah-trek",
    title: "Bsah Trek",
    series: "sil-vous-bled",
    price: 35,
    currency: "EUR",
    image: "/images/sil-vous-bled/s-il-vous-bled-bsah-trek.webp",
    description: "Star Trek, but the final frontier is the housing project.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
  {
    id: "svb-009",
    slug: "doux-bails",
    title: "Doux Bails",
    series: "sil-vous-bled",
    price: 35,
    currency: "EUR",
    image: "/images/sil-vous-bled/s-il-vous-bled-doux-bails.webp",
    description: "Sweet deals or sweet lease? The housing crisis in one pun.",
    dimensions: "50 x 70 cm",
    paper: "190g/m² matte archival paper",
  },
];

export const seriesInfo = {
  "tarpe-diem": {
    name: "Tarpe Diem",
    tagline: "Seize the day, before it seizes you back.",
    description:
      "Tarpe Diem is not a single statement. It is a collection of original artworks in which image and language derail together. A series of snapshots from an unraveling, wavering, and deeply complex society.",
    longDescription:
      "Here, surreal, fragmented, and intentionally unsettling visuals meet layered wordplay, homophonic distortions, and lexical sabotage. By reframing absurdism as a form of linguistic investigation, these works turn life into comedy precisely when the absurd becomes policy, while mirroring the emotional vertigo of our battered modern lives.",
    color: "dark",
  },
  "sil-vous-bled": {
    name: "S'il Vous Bled",
    tagline: "If you please, bleed a little.",
    description:
      "Drifting dreams living inside a joyful creative mess, steeped in warm Mediterranean poetic slang, floating over the Miscellanean Sea of human minds, and echoing French and Arabic lives through deliberate dyslexia and dystophonic signs.",
    longDescription:
      "Embracing the glitch as a feature and linguistic chaos as an opportunity, these works turn words into jokes and treat language as something living, unstable, and breakable. Pure wit smashing boundaries and colliding, gently but firmly, with cultural hybridity. Who gets to define what language and identity even mean?",
    color: "light",
  },
};

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsBySeries(series: string): Product[] {
  return products.filter((p) => p.series === series);
}

export function getRelatedProducts(
  currentSlug: string,
  series: string,
  limit: number = 8
): Product[] {
  return products
    .filter((p) => p.series === series && p.slug !== currentSlug)
    .slice(0, limit);
}
